
%Deventajas de la aspirina
afecta(aspirina, hemorragias).
afecta(aspirina, ulceras).
afecta(aspirina, higado).
afecta(aspirina, sistema_nervioso).

%Compuestos de una planta
contiene(planta, vitaminas).
contiene(planta, hormonas).
contiene(planta, minerales).
contiene(planta, metaloides).
contiene(planta, proteinas).
contiene(planta, oligoelementos).
contiene(planta, enzimas).
contiene(planta, alcaloides).

%de que estan echas las medicinas actuales
es_producido_por(aspirina, corteza_sauce).
es_producido_por(digitalina, digital).
es_producido_por(morfina, opio).
es_producido_por(bodeina, opio).
es_producido_por(emetina, ipeca).
es_producido_por(estricnina, nuezVomica).
es_producido_por(veratrina, eleboroBlanco).
es_producido_por(colquicina, colchico).
es_producido_por(atropina, belladona).
es_producido_por(quinina,quina).
es_producido_por(teobromina,cacao).
es_producido_por(esparteina, retama).
es_producido_por(cocaina,coca).
es_producido_por(mescalina, teyote).
es_producido_por(efedrina, efedra).
es_producido_por(hormonas, barbasco).
es_producido_por(lutenurina, nenufarAmarillo).
es_producido_por(disponina, name).
es_producido_por(tauremisina, artemisa).
es_producido_por(olitorisida, semuilla_yute).
es_producido_por(asido_lisergico, toloache).
es_producido_por(eucaliptol, eucalipto).
es_producido_por(vitaminaC, rosal).

%significado de efectos 
efecto(afrodisiaco, excita_apetito_sexual).
efecto(analgesico, quita_moderar_dolor).
efecto(anestesico, insensibiliza_cuerpo).
efecto(antidiarreico, controla_diarreas).
efecto(antiespasmodico, controla_espasmos_nerviosos).
efecto(antiflogistico, actua_contra_inflamaciones).
efecto(antipiretico, quita_disminuye_fiebre).
efecto(antiseptico, mata_tejidos).
efecto(aperitivo, produce_apetito).
efecto(astringente, hace_contraer_tejidos).
efecto(carminativa, evita_formacion_gases).
efecto(carminativa, provoca_expulsion_gases).
efecto(colagoga, ayuda_evacuacion_bilis).
efecto(depurativa, limpia_purifica_sangre).
efecto(diaforetica, provoca_transpiracion).
efecto(digestiva, favorece_digestion).
efecto(emética, provoca_nauseas_vomitos).
efecto(emoliente, suaviza_hidrata).
efecto(estupefaciente, aquieta_duerme_atonta).
efecto(expectorante, expulsa_flemas_mucosidades).
efecto(hemostatica, corta_detiene_hemorragias).
efecto(hepatica, favorece_funcion_higado).
efecto(laxante, purga_sin_diarrea).
efecto(narcotica, produce_sueno_pesado).
efecto(sedante, calma_dolores_intensos).
efecto(tonica, da_fuerza_vigor).
efecto(venenosa, insensibiliza_provoca_muerte).
efecto(vermifuga, expulsa_gusanos_intestinales).
efecto(vulneraria, cura_llagas_heridas).

%remedios de algunas plantas y como usarlas 
alivia(abrojo, afecciones_pecho, "cocer raiz y aplicar como agua de uso").
alivia(abrojo, inflamacion_ojos, "cocer raiz y aplicar como agua de uso").
alivia(abrojo, inflamacion_higado, "cocer raiz y aplicar como agua de uso").
alivia(acacia, dolor_garganta, "cortar tronco de arbol, dejar que la savia salga y se endurezca, despues chuparla").
alivia(acacia, tos, "cortar tronco de arbol, dejar que la savia salga y se endurezca, despues chuparla").
alivia(acacia, bronquitis, "cortar tronco de arbol, dejar que la savia salga y se endurezca, despues chuparla").
alivia(acacia, quemaduras, "revolver una pizca de polvo de goma arabiga con clara de huevo y aplicar en la quemadura").
alivia(acanto, picadura_arania, "aplicar sus hojas sobre la herida").
alivia(acanto, almorranas, "tomar te de sus hojas").
alivia(acanto, ardor_orina, "tomar te de sus hojas").
alivia(acanto, herida_golpe, "tomar te de sus hojas").
alivia(acanto, dispepsia, "tomar te de sus hojas").
alivia(acanto, disenteria, "tomar te de sus hojas").
alivia(aceitilla, cansansio_intelectual, "Tomarla como te").
alivia(aceitilla, depresion_nerviosa, "Tomarla como te").
alivia(achicoria, colicos_biliosos, "cocer las hojas y tomarlo como te").
alivia(achicoria, estrenimiento, "cocer las hojas y tomarlo como te").

favorece(abrojo, circulacion_de_sangre, "cocer raiz y aplicar como agua de uso").
favorece(achicoria, digestion, "cocer las hojas y tomarlo como te").

%listado de algunas enfermedades junto con su trtamiento
tratamiento(abscesos, malva).
tratamiento(absceso_hepatico, zarzaparrilla).
tratamiento(acidez_estomacal, anis).
tratamiento(acidez_estomacal, perejil).
tratamiento(acido_urico, sanguinaria).
tratamiento(acido_urico, limon).
tratamiento(acido_urico, sauco).
tratamiento(acne, arnica).
tratamiento(aftas, llanten).
tratamiento(aftas, fenogreco).
tratamiento(aftas, zarzamora).
tratamiento(agotamiento, salvia).
tratamiento(agotamiento, tilo).
tratamiento(agotamiento, valeriana).
tratamiento(agruras, yerbabuena).
tratamiento(agruras, manzanilla).
tratamiento(agruras, jugo_de_limon).
tratamiento(agruras, jugo_de_toronja).
tratamiento(albuminuria, pringue).
tratamiento(albuminuria, quina_roja).
tratamiento(albuminuria, encino_rojo).
tratamiento(alcoholismo, pimiento).
tratamiento(almorranas, salvia).
tratamiento(almorranas, hamamelis).
tratamiento(almorranas, sanguinaria).
tratamiento(almorranas, cola_de_caballo).
tratamiento(almorranas, arnica).
tratamiento(almorranas, toques).
tratamiento(almorranas, sauco).
tratamiento(anemia, ajenjo).
tratamiento(anemia, germen_de_trigo).
tratamiento(anemia, quina).
tratamiento(anemia, canela).
tratamiento(anemia, alholva).
tratamiento(anginas, eucalipto).
tratamiento(anginas, cebada).
tratamiento(anginas, salvia).
tratamiento(anginas, tabachin).
tratamiento(anginas, borraja).
tratamiento(anorexia, ajenjo).
tratamiento(anorexia, genciana).
tratamiento(anorexia, yerbabuena).
tratamiento(arteriosclerosis, limon).
tratamiento(arteriosclerosis, genciana).
tratamiento(arteriosclerosis, cardo).
tratamiento(arteriosclerosis, zarzaparrilla).
tratamiento(artritis, arnica).
tratamiento(artritis, chilacote).
tratamiento(artritis, alcanfor).
tratamiento(artritis, toronja).
tratamiento(asma, eucalipto).
tratamiento(asma, marrubio).
tratamiento(asma, toloache).
tratamiento(asma, oregano).
tratamiento(asma, ajenjo).
tratamiento(asma, salvia).
tratamiento(atonia_estomacal, lupulo).
tratamiento(atonia_estomacal, eucalipto).
tratamiento(atonia_estomacal, gusia).
tratamiento(bazo, uva).
tratamiento(bazo, cerezo).
tratamiento(boca_inflamacion, malva).
tratamiento(boca_inflamacion, rosa).
tratamiento(boca_inflamacion, limon).
tratamiento(boca_inflamacion, salvia).
tratamiento(boca_inflamacion, zarzamora).
tratamiento(estomatitis, rosa).
tratamiento(estomatitis, encina).
tratamiento(estomatitis, salvia).
tratamiento(estomatitis, zarzamora).
tratamiento(bronquitis, eucalipto).
tratamiento(bronquitis, borraja).
tratamiento(bronquitis, anacahuite).
tratamiento(bronquitis, gordolobo).
tratamiento(bronquitis, tilo).
tratamiento(bronquitis, benju).
tratamiento(bronquitis, marrubio).
tratamiento(bronquitis, rábano).
tratamiento(bronconeumonia, gordolobo).
tratamiento(bronconeumonia, eucalipto).
tratamiento(bronconeumonia, ipecacuana).
tratamiento(bronconeumonia, mostaza).
tratamiento(caida_de_cabello, ortiga).
tratamiento(caida_de_cabello, espinosilla).
tratamiento(caida_de_cabello, marrubio).
tratamiento(caida_de_cabello, romero).
tratamiento(calambres, anis).
tratamiento(calambres, tila).
tratamiento(calambres, manzanilla).
tratamiento(calambres, ajenjo).
tratamiento(calculos_biliares, diente_de_leon).
tratamiento(calculos_biliares, aceite_de_oliva).
tratamiento(calculos_biliares, retama).
tratamiento(calculos_renales, cabellos_de_elote).
tratamiento(calculos_renales, pringamosa).
tratamiento(calculos_renales, cola_de_caballo).
tratamiento(callos, ajo).
tratamiento(callos, cebolla).
tratamiento(caries, hiedra).
tratamiento(caries, cola_de_caballo).
tratamiento(caspa, ortiga).
tratamiento(caspa, limon).
tratamiento(caspa, romero).
tratamiento(cancer_de_utero, cuachalalate).
tratamiento(cancer_de_utero, llanten).
tratamiento(cancer_de_utero, siempreviva).
tratamiento(ciatica, mostaza).
tratamiento(ciatica, hiedra).
tratamiento(ciatica, sauce).
tratamiento(circulacion, totonil).
tratamiento(circulacion, sanguinaria).
tratamiento(circulacion, salvia).
tratamiento(circulacion, hamamelis).
tratamiento(cistitis, cola_de_caballo).
tratamiento(cistitis, doradilla).
tratamiento(cistitis, ajo).
tratamiento(cistitis, cabellos_de_elote).
tratamiento(colicos, menta).
tratamiento(colicos, hinojo).
tratamiento(colicos, manzanilla).
tratamiento(colicos, toronjil).
tratamiento(colicos, boldo).
tratamiento(colitis, linaza).
tratamiento(colitis, romero).
tratamiento(contusiones, arnica).
tratamiento(contusiones, hamamelis).
tratamiento(contusiones, laurel).
tratamiento(contusiones, brionia).
tratamiento(corazon, digital).
tratamiento(corazon, salvia).
tratamiento(corazon, nuez_de_kola).
tratamiento(corazon, tejocote).
tratamiento(depurativos_de_la_sangre, ucihcoriaca).
tratamiento(depurativos_de_la_sangre, diente_de_leon).
tratamiento(depurativos_de_la_sangre, apio).
tratamiento(depurativos_de_la_sangre, sanguinaria).
tratamiento(depurativos_de_la_sangre, zarzaparrilla).
tratamiento(diabetes, matiargue).
tratamiento(diabetes, tronadora).
tratamiento(diabetes, guarumbo).
tratamiento(diabetes, eucalipto).
tratamiento(diabetes, pata_de_vaca).
tratamiento(difteria, capulin).
tratamiento(difteria, mezquite).
tratamiento(difteria, tepeguaje).
tratamiento(difteria, tlachichinole).
tratamiento(diarrea, nogal).
tratamiento(diarrea, guayaba).
tratamiento(diarrea, canela).
tratamiento(diarrea, durazno).
tratamiento(diarrea, zarzamora).
tratamiento(diarrea, verbena).
tratamiento(diarrea, tlanchalagua).
tratamiento(diarrea_verosa, manzanilla).
tratamiento(diarrea_verosa, lino).
tratamiento(diarrea_verosa, siempreviva).
tratamiento(diarrea_verosa, toronjil).
tratamiento(diarrea_con_sangre, chaparro_amargoso).
tratamiento(diarrea_con_sangre, muicle).
tratamiento(diarrea_con_sangre, moralillo).
tratamiento(difteria, limon).
tratamiento(difteria, naranja).
tratamiento(disenteria, tamarindo).
tratamiento(disenteria, chaparro_amargoso).
tratamiento(disenteria, ipecacuana).
tratamiento(disenteria, cedron).
tratamiento(disenteria, guayaba).
tratamiento(dispesia, anis).
tratamiento(dispesia, menta).
tratamiento(dispesia, yerbabuena).
tratamiento(dispesia, diente_de_leon).
tratamiento(dispesia, hiera).
tratamiento(dispesia, quina).
tratamiento(dispesia, genciana).
tratamiento(dispesia, tabachin).
tratamiento(dispesia, ruibarbo).
tratamiento(dispesia, linaza).
tratamiento(sihay_dolor, anis_estrella).
tratamiento(sihay_dolor, valeriana).
tratamiento(sihay_dolor, manzanilla).
tratamiento(dolores_musculares, alcanfor).
tratamiento(empacho, tamarindo).
tratamiento(entiritis, linaza).
tratamiento(entiritis, cedron).
tratamiento(entiritis, llanten).
tratamiento(epilepsia, valeriana).
tratamiento(epistaxis, hierba_del_polo).
tratamiento(epistaxis, cebolla).
tratamiento(epistaxis, perejil).
tratamiento(erisipela, sauco).
tratamiento(erisipela, hiedra).
tratamiento(erisipela, zarzamora).
tratamiento(escarlatina, borraja).
tratamiento(escarlatina, sauco).
tratamiento(escarlatina, cebolla).
tratamiento(escorbuto, ajo).
tratamiento(escorbuto, limon).
tratamiento(escorbuto, berro).
tratamiento(escorbuto, cebolla).
tratamiento(estrenimiento, ciruela).
tratamiento(estrenimiento, linaza).
tratamiento(estrenimiento, chia).
tratamiento(estrenimiento, tamarindo).
tratamiento(estrenimiento, agar_agar).
tratamiento(faringitis, eucalipto).
tratamiento(faringitis, lavanda).
tratamiento(faringitis, anacahuite).
tratamiento(flatulencias, ajo).
tratamiento(flatulencias, tomillo).
tratamiento(flatulencias, yerbabuena).
tratamiento(flatulencias, toronjil).
tratamiento(flatulencias, limon).
tratamiento(flatulencias, ruibarbo).
tratamiento(flatulencias, ruda).
tratamiento(flatulencias, menta).
tratamiento(flebitis, arnica).
tratamiento(flebitis, alfalfa).
tratamiento(flebitis, lino).
tratamiento(flebitis, malva).
tratamiento(flebitis, sauco).
tratamiento(flebitis, quina).
tratamiento(flemas, oregano).
tratamiento(flemas, yerbabuena).
tratamiento(forunculos, fenogreco).
tratamiento(forunculos, malvavisco).
tratamiento(forunculos, hiedra).
tratamiento(grietas_del_ano, encina).
tratamiento(grietas_del_pezon, encina).
tratamiento(grietas_del_pezon, nogal).
tratamiento(grietas_del_pezon, mejorana).
tratamiento(gripe, eucalipto).
tratamiento(gripe, limon).
tratamiento(gripe, quinia).
tratamiento(gripe, zarzaparrilla).
tratamiento(gripe, calendula).
tratamiento(halitosis, hinojo).
tratamiento(halitosis, menta).
tratamiento(hemorragia_interna, mastuerzo).
tratamiento(hepatitis, retama).
tratamiento(hepatitis, boldo).
tratamiento(hepatitis, prodigiosa).
tratamiento(hepatitis, cascara_sagrada).
tratamiento(hernia, helecho).
tratamiento(hernia, ricino).
tratamiento(hernia, tabaco).
tratamiento(herpes, linaza).
tratamiento(herpes, llanten).
tratamiento(hemorroides, arnica).
tratamiento(hemorroides, hamamelis).
tratamiento(hidropesia, alcachofa).
tratamiento(hidropesia, retama).
tratamiento(hidropesia, eucalipto).
tratamiento(hidropesia, boldo).
tratamiento(hidropesia, ruibarbo).
tratamiento(higado_congestion, marrubio).
tratamiento(higado_congestion, boldo).
tratamiento(higado_congestion, doradilla).
tratamiento(higado_congestion, ruibarbo).
tratamiento(higado_colicos, manzanilla).
tratamiento(higado_bilis, lechuga).
tratamiento(higado_bilis, tila).
tratamiento(higado_ictericia, papaloquelite).
tratamiento(higado_ictericia, achicoria).
tratamiento(higado_ictericia, berros).
tratamiento(higado_ictericia, linaza).
tratamiento(higado_ictericia, retama).
tratamiento(higado_ictericia, teosonaste).
tratamiento(hipertension_alta, ajo).
tratamiento(hipertension_alta, esparrago).
tratamiento(hipertension_alta, alpiste).
tratamiento(hipertension_alta, muerdago).
tratamiento(hipotension_baja, miel).
tratamiento(hipotension_baja, nuez_de_kola).
tratamiento(hipotension_baja, crataegus).
tratamiento(hipotension_baja, acedera).
tratamiento(hipo, anis).
tratamiento(hipo, hinojo).
tratamiento(hipo, tila).
tratamiento(hipo, valeriana).
tratamiento(histerismo, azahar).
tratamiento(histerismo, beleño).
tratamiento(histerismo, gelsemio).
tratamiento(histerismo, tila).
tratamiento(histerismo, valeriana).
tratamiento(insomnio, pasiflora).
tratamiento(insomnio, azahar).
tratamiento(insomnio, menta).
tratamiento(insomnio, manzanilla).
tratamiento(insomnio, lechuga).
tratamiento(insomnio, tila).
tratamiento(intestino_atonia, genciana).
tratamiento(intestino_atonia, melisa).
tratamiento(impotencia_sexual, yohimbo).
tratamiento(impotencia_sexual, damiana).
tratamiento(impotencia_sexual, nuez_vomica).
tratamiento(impotencia_sexual, aguacate).
tratamiento(diarrea_con_sangre, chaparro_amargoso).
tratamiento(diarrea_con_sangre, muicle).
tratamiento(diarrea_con_sangre, moralillo).
tratamiento(difteria, limon).
tratamiento(difteria, naranja).
tratamiento(disenteria, tamarindo).
tratamiento(disenteria, chaparro_amargoso).
tratamiento(disenteria, ipecacuana).
tratamiento(disenteria, cedron).
tratamiento(disenteria, guayaba).
tratamiento(dispesia, anis).
tratamiento(dispesia, menta).
tratamiento(dispesia, yerbabuena).
tratamiento(dispesia, diente_de_leon).
tratamiento(dispesia, hiera).
tratamiento(dispesia, quina).
tratamiento(dispesia, genciana).
tratamiento(dispesia, tabachin).
tratamiento(dispesia, ruibarbo).
tratamiento(dispesia, linaza).
tratamiento(sihay_dolor, anis_estrella).
tratamiento(sihay_dolor, valeriana).
tratamiento(sihay_dolor, manzanilla).
tratamiento(dolores_musculares, alcanfor).
tratamiento(empacho, tamarindo).
tratamiento(entiritis, linaza).
tratamiento(entiritis, cedron).
tratamiento(entiritis, llanten).
tratamiento(epilepsia, valeriana).
tratamiento(epistaxis, hierba_del_polo).
tratamiento(epistaxis, cebolla).
tratamiento(epistaxis, perejil).
tratamiento(erisipela, sauco).
tratamiento(erisipela, hiedra).
tratamiento(erisipela, zarzamora).
tratamiento(escarlatina, borraja).
tratamiento(escarlatina, sauco).
tratamiento(escarlatina, cebolla).
tratamiento(escorbuto, ajo).
tratamiento(escorbuto, limon).
tratamiento(escorbuto, berro).
tratamiento(escorbuto, cebolla).
tratamiento(estrenimiento, ciruela).
tratamiento(estrenimiento, linaza).
tratamiento(estrenimiento, chia).
tratamiento(estrenimiento, tamarindo).
tratamiento(estrenimiento, agar_agar).
tratamiento(faringitis, eucalipto).
tratamiento(faringitis, lavanda).
tratamiento(faringitis, anacahuite).
tratamiento(flatulencias, ajo).
tratamiento(flatulencias, tomillo).
tratamiento(flatulencias, yerbabuena).
tratamiento(flatulencias, toronjil).
tratamiento(flatulencias, limon).
tratamiento(flatulencias, ruibarbo).
tratamiento(flatulencias, ruda).
tratamiento(flatulencias, menta).
tratamiento(flebitis, arnica).
tratamiento(flebitis, alfalfa).
tratamiento(flebitis, lino).
tratamiento(flebitis, malva).
tratamiento(flebitis, sauco).
tratamiento(flebitis, quina).
tratamiento(flemas, oregano).
tratamiento(flemas, yerbabuena).
tratamiento(forunculos, fenogreco).
tratamiento(forunculos, malvavisco).
tratamiento(forunculos, hiedra).
tratamiento(grietas_del_ano, encina).
tratamiento(grietas_del_pezon, encina).
tratamiento(grietas_del_pezon, nogal).
tratamiento(grietas_del_pezon, mejorana).
tratamiento(gripe, eucalipto).
tratamiento(gripe, limon).
tratamiento(gripe, quinia).
tratamiento(gripe, zarzaparrilla).
tratamiento(gripe, calendula).
tratamiento(halitosis, hinojo).
tratamiento(halitosis, menta).
tratamiento(hemorragia_interna, mastuerzo).
tratamiento(hepatitis, retama).
tratamiento(hepatitis, boldo).
tratamiento(hepatitis, prodigiosa).
tratamiento(hepatitis, cascara_sagrada).
tratamiento(hernia, helecho).
tratamiento(hernia, ricino).
tratamiento(hernia, tabaco).
tratamiento(herpes, linaza).
tratamiento(herpes, llanten).
tratamiento(hemorroides, arnica).
tratamiento(hemorroides, hamamelis).
tratamiento(hidropesia, alcachofa).
tratamiento(hidropesia, retama).
tratamiento(hidropesia, eucalipto).
tratamiento(hidropesia, boldo).
tratamiento(hidropesia, ruibarbo).
tratamiento(higado_congestion, marrubio).
tratamiento(higado_congestion, boldo).
tratamiento(higado_congestion, doradilla).
tratamiento(higado_congestion, ruibarbo).
tratamiento(higado_colicos, manzanilla).
tratamiento(higado_bilis, lechuga).
tratamiento(higado_bilis, tila).
tratamiento(higado_ictericia, papaloquelite).
tratamiento(higado_ictericia, achicoria).
tratamiento(higado_ictericia, berros).
tratamiento(higado_ictericia, linaza).
tratamiento(higado_ictericia, retama).
tratamiento(higado_ictericia, teosonaste).
tratamiento(hipertension_alta, ajo).
tratamiento(hipertension_alta, esparrago).
tratamiento(hipertension_alta, alpiste).
tratamiento(hipertension_alta, muerdago).
tratamiento(hipotension_baja, miel).
tratamiento(hipotension_baja, nuez_de_kola).
tratamiento(hipotension_baja, crataegus).
tratamiento(hipotension_baja, acedera).
tratamiento(hipo, anis).
tratamiento(hipo, hinojo).
tratamiento(hipo, tila).
tratamiento(hipo, valeriana).
tratamiento(histerismo, azahar).
tratamiento(histerismo, beleño).
tratamiento(histerismo, gelsemio).
tratamiento(histerismo, tila).
tratamiento(histerismo, valeriana).
tratamiento(insomnio, pasiflora).
tratamiento(insomnio, azahar).
tratamiento(insomnio, menta).
tratamiento(insomnio, manzanilla).
tratamiento(insomnio, lechuga).
tratamiento(insomnio, tila).
tratamiento(intestino_atonia, genciana).
tratamiento(intestino_atonia, melisa).
tratamiento(impotencia_sexual, yohimbo).
tratamiento(impotencia_sexual, damiana).
tratamiento(impotencia_sexual, nuez_vomica).
tratamiento(impotencia_sexual, aguacate).
tratamiento(sarampion, encina).
tratamiento(sarampion, salvia).
tratamiento(sarampion, tila).
tratamiento(sed, limon).
tratamiento(sed, tamarindo).
tratamiento(sed, pinole).
tratamiento(solitaria, semilla_de_calabaza).
tratamiento(solitaria, granado).
tratamiento(solitaria, coquito_de_aceite).
tratamiento(solitaria, helecho_macho).
tratamiento(sudoracion_excesiva, encina).
tratamiento(tifoidea, alcanfor).
tratamiento(tifoidea, borraja).
tratamiento(tifoidea, quina).
tratamiento(tifoidea, canela).
tratamiento(tifoidea, romero).
tratamiento(tifoidea, salvia).
tratamiento(tinia, berro).
tratamiento(tinia, tila).
tratamiento(tinia, toronjil).
tratamiento(tinia, salvia).
tratamiento(tos, eucalipto).
tratamiento(tos, capulin).
tratamiento(tos, cedron).
tratamiento(tos, salvia).
tratamiento(tos, malva).
tratamiento(tos, marrubio).
tratamiento(tos_ferina, gelsemio).
tratamiento(tos_ferina, quina).
tratamiento(tos_ferina, rabano).
tratamiento(tos_ferina, violeta).
tratamiento(tuberculosis, jugo_de_vastago_de_plantano_morado).
tratamiento(tuberculosis, mostaza).
tratamiento(tuberculosis, berro).
tratamiento(tuberculosis, ajo).
tratamiento(tuberculosis, eucalipto).
tratamiento(tuberculosis, pino).
tratamiento(tuberculosis, roble).
tratamiento(ulcera, cuachalalate).
tratamiento(ulcera, sanguinaria).
tratamiento(ulcera, cola_de_caballo).
tratamiento(ulcera, girasol).
tratamiento(urticaria, limon).
tratamiento(urticaria, ruibarbo).
tratamiento(varices, hamamelis).
tratamiento(varices, castano_de_indias).
tratamiento(varices, llanten).
tratamiento(varices, toronjil).
tratamiento(vejiga, apio).
tratamiento(vejiga, cipres).
tratamiento(vejiga, cola_de_caballo).
tratamiento(vejiga, ortiga).
tratamiento(vejiga, malva).
tratamiento(verrugas, leche_de_higuera).
tratamiento(verrugas, celidonia).
tratamiento(verrugas, nogal).
tratamiento(vertigo, haba).
tratamiento(vertigo, espino).
tratamiento(vertigo, albahaca).
tratamiento(vientre, borraja).
tratamiento(vientre, marrubio).
tratamiento(vientre, vetiveriana).
tratamiento(vientre, salvia).
tratamiento(vitiligo, berro).
tratamiento(vox, cilantro).
tratamiento(vox, ajo).
tratamiento(vox, limon).
tratamiento(vox, pino).
tratamiento(vitaminas_carencia, alfalfa).
tratamiento(vitaminas_carencia, espinacas).
tratamiento(vitaminas_carencia, berro).
tratamiento(vitaminas_carencia, cebolla).
tratamiento(vitaminas_carencia, limon).
tratamiento(vitaminas_carencia, zanahoria).
tratamiento(vitaminas_carencia, retue).
tratamiento(vitaminas_carencia, bacalao).

%Explicacion de formas de uso de las plantas
forma_uso(cocimiento, "Poner a hervir en barro o peltre en agua, la hierba o raíz, por 10 minutos. Dejar reposar unos 5 minutos y tomarlo ya colado").
forma_uso(infusion, "Hervir el agua en un recipiente y vaciarla ya hervida y todavia hirviendo en otro donde se depositará previamente la planta. Tapar y dejar en reposo 5 minutos. Colar y tomar").
forma_uso(maceracion, "Triturar la planta y sumergirla en poca agua y que remoje para que suelte las sustancias").
forma_uso(jarabe, "Hervir la planta en agua 10 minutos, ponerle azúcar (tanto y medio la cantidad de agua), y una vez hervida dejarla en fuego suave teniendo 10% alcohol en frío. Se enmasa para su uso posterior").
forma_uso(tintura, "En frasco que pueda taparse con tapón de corcho, se pone la planta desmenuzada o triturada y se le echa alcohol de caña, se agita y se le añade agua destilada o de lluvia (25 g por cada 95 g de alcohol) y se deja reposar en lo oscuro una o dos semanas, agitando de vez en cuando. Luego se filtra con algodón o estopilla y listo").
forma_uso(jugo, "Exprimir las plantas en un trapo limpio y ya").
forma_uso(horchata, "Se muelen las semillas agregándole poco a poco agua para formar una masilla. Se cuela luego en cedazo, se endulza y se le agrega agua para tomarla").

%PLANTQAS ASIGNADAS 
planta(anis, colicos).
planta(amapola_amarilla).
planta(amate).

alivia(anis, desinfectante_boca).
alivia(anis, antiflatulento).
alivia(anis, lactancia).
alivia(amapola_amarilla, hipnotica).
alivia(amapola_amarilla, sedante).
alivia(amapola_amarilla, calmar_dolores_intestinales).
alivia(amapola_amarilla, antidiarreico).
alivia(amate, curar_reumatismos).
alivia(amate, botar_solitaria).

preparacion(anis, te).
preparacion(amapola_amarilla, te).
preparacion(amate, cataplasma).
preparacion(amate, combinacion_leche_higo_vaca_miel).